export const WORDS = [
  { se: "å", en: "small river" },
  { se: "använda", en: "use" },
  { se: "använda", en: "use" },
  { se: "apa", en: "monkey" },
  { se: "arbeten", en: "job" },
  { se: "bastu", en: "sauna" },
  { se: "blåsa", en: "blow" },
  { se: "bra", en: "good" },
  { se: "bröllop", en: "wedding" },
  { se: "dator", en: "computer" },
  { se: "döda", en: "kill" },
  { se: "farthinder", en: "speed bump" },
  { se: "fisk", en: "fish" },
  { se: "fladdermus", en: "bat" },
  { se: "flyta", en: "float" },
  { se: "försäkring", en: "insurance" },
  { se: "frysa", en: "freeze" },
  { se: "gå", en: "go" },
  { se: "gå", en: "walk" },
  { se: "ge", en: "give" },
  { se: "gnida", en: "rub" },
  { se: "göra", en: "make" },
  { se: "gråta", en: "cry" },
  { se: "haj", en: "shark" },
  { se: "hålla", en: "hold" },
  { se: "hav", en: "sea" },
  { se: "helg", en: "weekend" },
  { se: "himmel", en: "sky" },
  { se: "höra", en: "hear" },
  { se: "idag", en: "today" },
  { se: "imorgon", en: "tomorrow" },
  { se: "kasta", en: "throw" },
  { se: "klämma", en: "squeeze" },
  { se: "klocka", en: "clock" },
  { se: "klocka", en: "clock" },
  { se: "kock", en: "chef" },
  { se: "komma", en: "come" },
  { se: "komma", en: "come" },
  { se: "kudde", en: "pillow" },
  { se: "kyckling", en: "chicken" },
  { se: "långt", en: "far" },
  { se: "lugn", en: "calm" },
  { se: "lukta", en: "smell" },
  { se: "lukta", en: "smell" },
  { se: "mjukvaruutvecklare", en: "software developer" },
  { se: "nagellacksborttagningmedel", en: "nail polish" },
  { se: "ö", en: "island" },
  { se: "öl", en: "beer" },
  { se: "ost", en: "cheese" },
  { se: "play", en: "play" },
  { se: "programmerare", en: "programmer" },
  { se: "rak", en: "straight" },
  { se: "säga", en: "say" },
  { se: "se", en: "see" },
  { se: "sjö", en: "lake" },
  { se: "sjuksköterska", en: "nurse" },
  { se: "sjunga", en: "sing" },
  { se: "skål", en: "bowl" },
  { se: "skära", en: "cut" },
  { se: "skärgård", en: "archipelago" },
  { se: "skepp", en: "ship" },
  { se: "sköldpadda", en: "turtle" },
  { se: "skratta", en: "laugh" },
  { se: "slut", en: "end" },
  { se: "smutsig", en: "dirty" },
  { se: "sol", en: "sun" },
  { se: "sommarstuga", en: "summer house" },
  { se: "sova", en: "sleep" },
  { se: "stå", en: "stand" },
  { se: "stjärna", en: "star" },
  { se: "sy", en: "sew" },
  { se: "tänka", en: "think" },
  { se: "torka", en: "wipe" },
  { se: "torr", en: "dry" },
  { se: "tvätta", en: "wash" },
  { se: "ursäkta", en: "excuse me" },
  { se: "utomjording", en: "alien" },
  { se: "vacker", en: "beautiful" },
  { se: "vecka", en: "week" },
  { se: "vecka", en: "week" }
];
