export const WORDS = [
  // { se: "apa", en: "monkey" },
  // { se: "arbeten", en: "job" },
  // { se: "blåsa", en: "blow" },
  // { se: "bröllop", en: "wedding" },
  // { se: "dator", en: "computer" },
  // { se: "döda", en: "kill" },
  // { se: "farthinder", en: "speed bump" },
  // { se: "fisk", en: "fish" },
  // { se: "flyta", en: "float" },
  // { se: "försäkring", en: "insurance" },
  // { se: "frysa", en: "freeze" },
  // { se: "gå", en: "walk" },
  // { se: "ge", en: "give" },
  // { se: "gnida", en: "rub" },
  // { se: "hålla", en: "hold" },
  // { se: "helg", en: "weekend" },
  // { se: "höra", en: "hear" },
  // { se: "kasta", en: "throw" },
  // { se: "klämma", en: "squeeze" },
  // { se: "kock", en: "chef" },
  // { se: "komma", en: "come" },
  // { se: "kudde", en: "pillow" },
  // { se: "kyckling", en: "chicken" },
  // { se: "lukta", en: "smell" },
  // { se: "lukta", en: "smell" },
  // { se: "nagellacksborttagningmedel", en: "nail polish" },
  // { se: "öl", en: "beer" },
  // { se: "ost", en: "cheese" },
  // { se: "play", en: "play" },
  // { se: "rak", en: "straight" },
  // { se: "säga", en: "say" },
  // { se: "sjuksköterska", en: "nurse" },
  // { se: "sjunga", en: "sing" },
  // { se: "skål", en: "bowl" },
  // { se: "skära", en: "cut" },
  // { se: "skepp", en: "ship" },
  // { se: "sköldpadda", en: "turtle" },
  // { se: "skratta", en: "laugh" },
  // { se: "slut", en: "end" },
  // { se: "smutsig", en: "dirty" },
  // { se: "sol", en: "sun" },
  // { se: "sova", en: "sleep" },
  // { se: "stå", en: "stand" },
  // { se: "stjärna", en: "star" },
  // { se: "sy", en: "sew" },
  // { se: "tänka", en: "think" },
  // { se: "torka", en: "wipe" },
  { se: "torr", en: "dry" },
  // { se: "tvätta", en: "wash" },
  // { se: "ursäkta", en: "excuse me" },
  { se: "klumpig", en: "clumsy" }
];
